version: '3'

services:
    main-server:
        build: main-server
        ports:
            - "8000:8000"
        volumes:
            - ./main-server:/app
    sandbox-server:
        build: sandbox-server
        ports:
            - "3000"
        volumes:
            - ./sandbox-server:/app
            - ./main-server/code:/app/code
            - /var/run/docker.sock:/var/run/docker.sock

